server:
  port: 8091
  tomcat:
    max-threads: 10

feign:
  sentinel:
    enabled: true

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    sentinel:
      transport:
        port: 9999 #注意，sentinel默认懒加载，需要第一次访问微服务之后才会被注册到sentinel控制台进行实时监控
        dashboard: 127.0.0.1:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848